services:
  django:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "scoreapp.asgi:application"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: scoreapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:
  static_volume:
  media_volume: