# Generated by Django 5.1.6 on 2025-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_score_remove_player_score_scoreentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreentry',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
