# Generated by Django 5.1.6 on 2025-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_scoreentry_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='rank',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
