# Generated by Django 5.1.6 on 2025-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_alter_scoreentry_rank_alter_scoreentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='rank',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
